### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by MiguelAspis** [MiguelAspis/SherlockQuotes#1]
Front-end(React)
- [ ] Create project
- [ ] Define components
- [ ] Receive user input
- [ ] Style the app
- [ ] Show Sherlock quote
Back-end(Node)
-[ ] Receive text from https://sherlock-holm.es/
- [ ] Clean up text
- [ ] Connect with Front-end
- [ ] Find keywords in user input with IBM Watson
- [ ] Search keywords through sherlock stories
- [ ] Return quote
